model_list:
  - model_name: Claude Opus 4.1 (20250805)
    litellm_params:
      model: bedrock/us.anthropic.claude-opus-4-1-20250805-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION
      rpm: 2
      allowed_openai_params:
        - tools
  - model_name: DeepSeek R1
    litellm_params:
      model: bedrock/us.deepseek.r1-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION
      rpm: 10
      allowed_openai_params:
        - tools
    model_info:
      max_tokens: 4096
      max_input_tokens: 8192
      max_output_tokens: 4096
      max_batch_total_tokens: 8192
  - model_name: gpt-oss-120b
    litellm_params:
      model: bedrock/openai.gpt-oss-120b-1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION
      rpm: 12
    model_info:
      max_tokens: 4096
      max_input_tokens: 8192
      max_output_tokens: 4096
      max_batch_total_tokens: 8192
general_settings:
  user_header_name: X-OpenWebUI-User-Name
  store_model_in_db: true
  store_prompts_in_spend_logs: true
